name: push-workflow
on: push #이벤트선택해서 트리거 선택, push는 active type없음

jobs: #실행 시킬 job집합
  push-job:
    runs-on: ubuntu-latest #runs-on이 우분투에서 실행
    steps: #step 집합
      - name: step1 #각 step마다 명시적으로 지정해줘도 되고 안해도 됨
        run: echo hello world
      - name: step2
        run: | #<- 멀티라인 커맨드 가능
          echo hello
          echo jongbin
