name: context
on: workflow_dispatch

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: github context
        run: echo '${{ toJSON(github) }}'
      - name: check github context
        run: |
          echo ${{ github.repository}}
          echo ${{ github.event_name}}
          echo ${{ github.triggering_actor}}

        #각각 context가 javascript객체라서 출력할려면 객체를 문자열로 반환해줘야함
        #깁헙액션에서는 toJSON메서드 사용
        #정보에 다양한 정보가 존재함 여기서 유연하게 뽑아서 사용가능
