name: create-repo
on:
  workflow_dispatch:
    inputs:
      prefix:
        description: "set repo prefix"
        required: true
        default: "service"
        type: choice
        options:
          - example
          - service
      name:
        description: "set repo name"
        required: true
        default: "github-actions"
        type: string

jobs:
  create-repo-automation:
    runs-on: ubuntu-latest
    steps:
      - name: gh auth login # GitHub 권한 가져오기
        run: |
          echo ${{ secrets.PERSONAL_ACCESS_TOKEN }} | gh auth login --with-token
      - name: create-repo # 입력받은 input 값으로 repo 생성
        run: |
          gh repo create NTbell-action/${{ inputs.prefix }}-${{ inputs.name }} --public --add-readme
