name: pull-request-workflow
on: pull_request

jobs: #실행 시킬 job집합
  pull-request-job:
    runs-on: ubuntu-latest #runs-on이 우분투에서 실행
    steps: #step 집합
      - name: step1 #각 step마다 명시적으로 지정해줘도 되고 안해도 됨
        run: echo hello world
      - name: step2
        run: |
          echo hello
          echo jongbin
